version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/ai-agent

ai-service:
  build: ./ai-service
  ports:
    - "8000:8000"
  environment:
    - GROQ_API_KEY=${GROQ_API_KEY}
